version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=EmployeeMatala2025!
    ports:
      - "1433:1433"
    networks:
      - ems-network

  api:
    build:
      context: .
      dockerfile: EmployeeManagementSystem.API/Dockerfile
    container_name: employee_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080
      - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=EmployeeDb;User Id=sa;Password=EmployeeMatala2025!;TrustServerCertificate=True;
    ports:
      - "8081:8080"
    depends_on:
      - sqlserver
    networks:
      - ems-network

networks:
  ems-network:
    driver: bridge